# Welcome to Jekyll!

# Website settings
title: Anshuman Bhartiya
description: Anshuman Bhartiya's personal website
keywords: Security,Automation,Docker,Kubernetes,Bug Bounty,DevSecOps,SecDevOps
baseurl:  "" # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://anshumanbh.github.io/  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
# img_path: /blog/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Anshuman Bhartiya  # Be used at blog posts' author.
  first_name: Anshuman  # Be used at index page about me section.
  last_name: Bhartiya  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: anshumanbh  # Leave blank if you don't have now
  linkedin_id: anshumanbhartiya # Leave blank if you don't have now
  facebook_username: anshuman.bhartiya  # Leave blank if you don't have now
  twitter_username: anshuman_bh  # Leave blank if you don't have now
  email: anshuman.bhartiya@gmail.com  # Leave blank if you don't have now
  cv: #http://cv.jarrekk.com  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  hackerone_username: anshuman_bh
  bugcrowd_username: anshuman_bh
  skill_icon1:
    - name: icon-docker
    - name: icon-aws
  skill_icon2:
    - name: icon-google
    - name: icon-go
  desc: I love Security, Automation, Docker, Kubernetes and Bug Bounties. I believe in Innovation, Challenges and Changes.  # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: anshumanbhartiya

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: UA-112014961-1

## google optimize
go:
  # id: 2281962420

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
# donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink:    /:year/:month/:day/:title/